version: "3"
services:
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
    kafka:
        image: wurstmeister/kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        depends_on:
            - zookeeper
    consumer:
        build: consumer/.
        environment:
            - "SPRING_PROFILES_ACTIVE=${ACTIVE_PROFILE}"
        ports:
            - "9091:9091"
        depends_on:
            - kafka
    producer:
        build: producer/.
        environment:
            - "SPRING_PROFILES_ACTIVE=${ACTIVE_PROFILE}"
        ports:
            - "8081:8081"
        depends_on:
            - kafka