zuul:
  prefix: /api
  routes:
    producer:
      path: /producer/**
      serviceId: PRODUCER
    consumer:
      path: /consumer/**
      url: http://localhost:9091

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
  instance:
    hostname: localhost

server:
  port: 8079

spring:
  application:
    name: zuul-service
