server:
    port: 8070
spring:
    application:
        name: eureka-service
eureka:
    client:
        registerWithEureka: false
        fetchRegistry: false
        server:
            waitTimeInMsWhenSyncEmpty: 0
        serviceUrl:
            defaultZone: http://localhost:8070/eureka/